# Generated by Django 5.2.10 on 2026-06-09 19:56

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.halfvec
import pgvector.django.indexes
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("data_room", "0028_doc_json_bilanz_mapped_split_status"),
    ]

    operations = [
        # Hand-edited: the pgvector extension must exist before the halfvec
        # column and HNSW index below can be created. CreateExtension runs
        # CREATE EXTENSION IF NOT EXISTS, so pre-provisioned databases
        # (e.g. extension installed via template1 or ansible) are a no-op.
        CreateExtension("vector"),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("collection_name", models.CharField(db_index=True, max_length=128)),
                ("document_id", models.BigIntegerField(db_index=True)),
                ("project_id", models.BigIntegerField(blank=True, db_index=True, null=True)),
                ("chunk_id", models.IntegerField(help_text="Sequential chunk ID within a document")),
                ("content", models.TextField()),
                ("original_content", models.TextField(blank=True, default="")),
                ("raw_section", models.TextField(blank=True, default="")),
                ("document_path", models.TextField(blank=True, default="")),
                ("image_path", models.TextField(blank=True, default="")),
                ("page_number", models.IntegerField(blank=True, null=True)),
                ("has_context", models.BooleanField(default=False)),
                ("embedding", pgvector.django.halfvec.HalfVectorField(dimensions=3072)),
                ("search_vector", django.contrib.postgres.search.SearchVectorField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="data_room.protectedclientdocument",
                    ),
                ),
                (
                    "project_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="data_room.protectedprojectdocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Chunk",
                "verbose_name_plural": "Document Chunks",
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="scribe_chunk_emb_hnsw",
                        opclasses=["halfvec_cosine_ops"],
                    ),
                    django.contrib.postgres.indexes.GinIndex(fields=["search_vector"], name="scribe_chunk_search_gin"),
                    models.Index(
                        fields=["collection_name", "document_id", "chunk_id"], name="scribe_docu_collect_389149_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("collection_name", "document_id", "chunk_id"),
                        name="scribe_unique_chunk_per_collection_doc",
                    )
                ],
            },
        ),
    ]
